# Generated by Django 3.1.7 on 2021-03-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_prep_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepe',
            name='recipe',
            field=models.TextField(default='Przykładowy przepis:\n\t1. Przygotuj składniki\n\t2. Wymieszaj\n\t3. Gotowe!'),
        ),
    ]
