# Generated by Django 3.1.7 on 2021-03-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_prep_app', '0002_auto_20210318_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('pub_date', models.DateField()),
                ('description', models.TextField()),
                ('recipe', models.TextField(default='Przykładowy przepis:\n1. Przygotuj składniki\n2. Wymieszaj\n3. Gotowe!')),
            ],
        ),
        migrations.DeleteModel(
            name='Recepe',
        ),
    ]
