# Generated by Django 3.1.7 on 2021-03-18 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal_prep_app', '0003_auto_20210318_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0, help_text='Amount of ingredient')),
                ('short_description', models.CharField(max_length=40)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_name', to='meal_prep_app.recipe')),
            ],
        ),
    ]
