# Generated by Django 3.1.7 on 2021-03-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_prep_app', '0004_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the ingredient', max_length=30, unique=True)),
                ('kind', models.CharField(choices=[(0, 'mass'), (1, 'volume')], max_length=20)),
            ],
        ),
    ]
