# Generated by Django 3.1.7 on 2021-03-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_prep_app', '0006_auto_20210318_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(0, 'mass'), (1, 'volume'), (2, 'countable')]),
        ),
    ]
