# Generated by Django 3.1.7 on 2021-03-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_prep_app', '0007_auto_20210318_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='kind',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.PositiveSmallIntegerField(choices=[(0, ''), (1, 'g'), (2, 'kg'), (3, 'l'), (4, 'ml'), (5, 'szklanka'), (6, 'łyżka'), (7, 'łyżeczka')], default=0),
        ),
    ]
