# Generated by Django 3.1.7 on 2021-03-18 13:32

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meal_prep_app', '0009_auto_20210318_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_pk', to='meal_prep_app.ingredient'),
        ),
        migrations.AlterField(
            model_name='amount',
            name='short_description',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=multiselectfield.db.fields.MultiSelectField(default=0, help_text='Choose units which will be available to chose for that ingredient.', max_length=200, verbose_name=[(0, ''), (1, 'g'), (2, 'kg'), (3, 'l'), (4, 'ml'), (5, 'szklanka'), (6, 'łyżka'), (7, 'łyżeczka')]),
        ),
    ]
