# Generated by Django 3.1.7 on 2021-03-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_prep_app', '0011_auto_20210318_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Amount of ingredient', max_digits=2),
        ),
        migrations.AlterField(
            model_name='amount',
            name='unit',
            field=models.PositiveSmallIntegerField(choices=[(0, ''), (1, 'g'), (2, 'kg'), (3, 'l'), (4, 'ml'), (5, 'szklanka'), (6, 'łyżka'), (7, 'łyżeczka'), (8, 'ząbek')], default=0),
        ),
    ]
