# Generated by Django 3.1.7 on 2021-03-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_prep_app', '0012_auto_20210318_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
    ]
