# Generated by Django 3.1.7 on 2021-03-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_prep_app', '0015_auto_20210318_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='unit',
            field=models.CharField(choices=[('', ''), ('g', 'g'), ('kg', 'kg'), ('l', 'l'), ('ml', 'ml'), ('szklanka', 'szklanka'), ('łyżka', 'łyżka'), ('łyżeczka', 'łyżeczka'), ('ząbek', 'ząbek')], default='', max_length=15),
        ),
    ]
