# Generated by Django 3.1.7 on 2021-03-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_prep_app', '0016_auto_20210319_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0, help_text='Amount of ingredient'),
        ),
        migrations.AlterField(
            model_name='amount',
            name='unit',
            field=models.CharField(blank=True, choices=[('', ''), ('g', 'g'), ('kg', 'kg'), ('l', 'l'), ('ml', 'ml'), ('szklanka', 'szklanka'), ('łyżka', 'łyżka'), ('łyżeczka', 'łyżeczka'), ('ząbek', 'ząbek')], default='', max_length=15),
        ),
    ]
