# Generated by Django 3.1.7 on 2021-03-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_prep_app', '0017_auto_20210319_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='amount',
            field=models.FloatField(default=0.0, help_text='Amount of ingredient'),
        ),
    ]
