# Generated by Django 3.1.7 on 2021-03-19 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_prep_app', '0018_auto_20210319_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation_time',
            field=models.DurationField(default=datetime.timedelta(0, 3600)),
        ),
    ]
