# Generated by Django 3.1.7 on 2021-03-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_prep_app', '0019_recipe_preparation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='unit',
            field=models.CharField(blank=True, choices=[('', ''), ('g', 'g'), ('kg', 'kg'), ('l', 'l'), ('ml', 'ml'), ('szklanka', 'szklanka'), ('łyżka', 'łyżka'), ('łyżeczka', 'łyżeczka'), ('ząbek', 'ząbek'), ('szczypta', 'szczypta')], default='', max_length=15),
        ),
    ]
