# Generated by Django 3.1.7 on 2021-03-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_prep_app', '0022_recipelist_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='people',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
