# Generated by Django 3.1.7 on 2021-06-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_prep_app', '0023_recipe_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
