# Generated by Django 3.1.7 on 2021-06-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_prep_app', '0031_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
