# Generated by Django 3.1.7 on 2021-06-15 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal_prep_app', '0032_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False)),
                ('amount', models.FloatField(default=0.0, help_text='Amount of ingredient')),
                ('unit', models.CharField(blank=True, choices=[('', ''), ('g', 'g'), ('kg', 'kg'), ('l', 'l'), ('ml', 'ml'), ('szklanka', 'szklanka'), ('łyżka', 'łyżka'), ('łyżeczka', 'łyżeczka'), ('ząbek', 'ząbek'), ('szczypta', 'szczypta')], default='', max_length=15)),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meal_prep_app.ingredient')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_prep_app.shoppinglist')),
            ],
        ),
    ]
