# Generated by Django 3.1.7 on 2021-06-15 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_prep_app', '0033_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='amounts',
        ),
    ]
