# Generated by Django 3.1.7 on 2021-06-21 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal_prep_app', '0035_auto_20210615_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='recipes',
        ),
        migrations.AlterField(
            model_name='amount',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts', to='meal_prep_app.recipe'),
        ),
    ]
