# Generated by Django 3.1.7 on 2021-06-21 19:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meal_prep_app', '0036_auto_20210621_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipelist',
            name='recipes',
            field=models.ManyToManyField(related_name='recipe_lists', to='meal_prep_app.Recipe'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='recipe_lists',
            field=models.ManyToManyField(blank=True, related_name='shopping_lists', to='meal_prep_app.RecipeList'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='user',
            field=models.ManyToManyField(related_name='shopping_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
